storage:
  dbPath: ./db
  journal:
    enabled: true
  directoryPerDB: true
systemLog:
  destination: file
  path: ./db/mongod.log
  logAppend: true
net:
  bindIp: 127.0.0.1
  port: 30000
setParameter:
  enableLocalhostAuthBypass: false
