#!/usr/bin/env node
var Application = require('./lib/application');

var env = process.argv[2];
process.vars = {
  env: env
};

var app = new Application();
app.init(function() {
  global.app = app;
  app.start();
});
