#!/usr/bin/env node
var mongoose = require('mongoose');
var readConfig = require('read-config');

var config = readConfig('./config/config.json');
var devices = readConfig('./config/devices.json');
var configdb = readConfig('./config/configdb.yaml');

global._config = config;
global._config.devices = devices.devices;

// Initialize database.
var env = process.argv[2];
process.vars = {
  env: env
};

var base = (env === 'production') ? config.db.base.prod : config.db.base.dev;
var dbhost = configdb.net.bindIp;
var dbport = configdb.net.port;
var connString = `mongodb://${dbhost}:${dbport}/${base}`;
mongoose.connect(connString);
var db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() {
  console.log(`Connected to DB on ${dbhost}:${dbport}/${base}`);

  var port = (env === 'production') ? config.port.prod : config.port.dev;

  var app = require('./app');
  app.set('env', env);
  app.set('port', port);

  var server = app.listen(port, function() {
    console.log("Local server listeting on port " + port);
  });
});
